# permissions for end users to edit notifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: notifier-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-event-operator
    app.kubernetes.io/part-of: kube-event-operator
    app.kubernetes.io/managed-by: kustomize
  name: notifier-editor-role
rules:
- apiGroups:
  - api.chil-pavn.online
  resources:
  - notifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.chil-pavn.online
  resources:
  - notifiers/status
  verbs:
  - get
